### ISSUE TITLE
Entity colour

### ISSUE THREAD

**Issue by drashish87** [andyblac/UI-Minimalist-Custom-Cards#14]
Hi is it possible to have the entity icon coloured even when off or permanently coloured like for a scene? At present the icon is olny coloured when on? Thank you for your lovely work!

      entity_3:
        entity_id: light.bathroom_light
        ulm_custom_card_andyblac_room_icon_color_on: yellow

Tried this, but doesnt work
   ulm_custom_card_andyblac_room_icon_color_off: yellow

**Comment by andyblac** [comment]
ok, I've added sokmething to the dev branch

to just use normal colours, use...
<img width="293" alt="Screenshot 2024-02-19 at 11 16 38" src="https://github.com/andyblac/UI-Minimalist-Custom-Cards/assets/77936/a8f5325e-f324-4b7d-b003-6d4a3bb7d481">
```yaml
      entity_3:
        entity_id: light.front_garden_light
        ulm_custom_card_andyblac_room_icon_color: amber
```

you can also use custom colours and brightness, by using something like
<img width="290" alt="Screenshot 2024-02-19 at 11 02 49" src="https://github.com/andyblac/UI-Minimalist-Custom-Cards/assets/77936/a91ae023-92ea-4a86-82fe-4a34853a3642">
```yaml
      entity_3:
        entity_id: light.front_garden_light
        ulm_custom_card_andyblac_room_icon_color: rgba(0,0,255,1)
```

**Comment by drashish87** [comment]
Thanks for some reason its not working for me.

Does it work if one of the entities is for a script too?

**Comment by andyblac** [comment]
I have not tried with a script, but I don't see why it would make any difference. Are you sure you grab it from the dev branch ?

**Comment by andyblac** [comment]
script works fine
<img width="332" alt="Screenshot 2024-02-19 at 21 24 12" src="https://github.com/andyblac/UI-Minimalist-Custom-Cards/assets/77936/ad4c98ab-151c-4530-862e-6c5b478dc641">
```yaml
  # Front Garden
  - type: custom:button-card
    view_layout:
      grid-area: room1
    template:
      - custom_card_andyblac_room
    name: Front Garden
    icon: mdi:flower
    tap_action:
      action: navigate
      navigation_path: front-garden
    variables:
      ulm_custom_card_andyblac_room_color: green
      sensor_label_1: sensor.front_garden_motion_sensor_temperature
      # sensor_label_2: sensor.front_garden_soil_sensor_humidity
      sensor_label_3: sensor.front_garden_motion_sensor_illuminance_lux
      sensor_1:
        entity_id: binary_sensor.front_door
      sensor_2:
        entity_id: binary_sensor.front_garden_motion_sensor_occupancy
        templates:
          - motion_animation
      entity_3:
        entity_id: script.garage_wall_light
        ulm_custom_card_andyblac_room_icon_color: rgb(0,0,255)
```

**Comment by drashish87** [comment]
> I have not tried with a script, but I don't see why it would make any difference. Are you sure you grab it from the dev branch ?
> 
> But try with a light for now just to test.

Yes # v2.2.1, I had refreshed yaml config under developer tools but it dint work.
Restarting HA did the trick, Thank you.

Lastly, how do you get the shower animation to work?
<img width="203" alt="Screenshot 2024-02-19 at 21 36 48" src="https://github.com/andyblac/UI-Minimalist-Custom-Cards/assets/136771698/0ff4c77e-dd34-4e4c-9ecd-8c0826ab89b2">


```
            - type: 'custom:button-card'
              template:
                - custom_card_andyblac_room
                - yellow_no_state
              name: "2nd Floor Bathroom"
              icon: mdi:shower-head
              templates:
                - shower_animation
              tap_action:
                action: navigate
                navigation_path: '/ui-lovelace-minimalist/2ndfloorbathroom'
              variables:
                ulm_custom_card_andyblac_room_use_small_label_font: true
                sensor_label_1: sensor.2nd_floor_bathroom_temperature
                sensor_label_2: sensor.2nd_floor_bathroom_humidity
```

**Comment by andyblac** [comment]
here's my wet room code
```yaml
  # Wetroom
  - type: custom:button-card
    view_layout:
      grid-area: room9
    template:
      - custom_card_andyblac_room
      - shower_animation
    name: "Wet Room"
    entity: binary_sensor.slave_dhw_active_boiler_otgw
    tap_action:
      action: navigate
      navigation_path: wetroom
    variables:
      ulm_custom_card_andyblac_room_color: rgb(77, 195, 255)
      sensor_label_1: sensor.wetroom_sensor_temperature
      sensor_label_2: sensor.wetroom_sensor_humidity
      sensor_label_3: sensor.wetroom_humidity_derivative
      sensor_1:
        entity_id: input_boolean.hot_water_toggle
        tap_action:
          action: toggle
      entity_3:
        entity_id: light.wetroom_lights
        ulm_custom_card_andyblac_room_icon_color_on: amber
      entity_4:
        entity_id: switch.wetroom_extractor_boost
        ulm_custom_card_andyblac_room_icon_color_on: rgb(77, 195, 255)
        templates:
          - fan_animation
```
