### ISSUE TITLE
FR: More options for ulm_custom_card_andyblac_room_color_on possible?

### ISSUE THREAD

**Issue by FelixArndt** [andyblac/UI-Minimalist-Custom-Cards#9]
Hey Andy,

which entity is decisive/crucial for this option: ulm_custom_card_andyblac_room_color_on?

It would be awesome, if the room-color changes if a light in a room is turned on and it would grey again if all lights in a room goes off.

Example light turned on:
![grafik](https://github.com/andyblac/UI-Minimalist-Custom-Cards/assets/84038178/418c815b-4403-4bc4-88d9-370d4dc67667)

Example light turned off:
![grafik](https://github.com/andyblac/UI-Minimalist-Custom-Cards/assets/84038178/ed606603-ceb6-4e2a-ada4-1c1dd056f7cb)

Thanks in advance!
Felix

**Comment by andyblac** [comment]
hi, for this to work the room need an entity, like this

```
  - type: custom:button-card
    view_layout:
      grid-area: room10
    template:
      - custom_card_andyblac_room
    name: Office
    icon: mdi:desk
    entity: light.office_dimmer
    variables:
      ulm_custom_card_andyblac_room_color_on: blue
```
